# Generated by Django 4.0.5 on 2022-06-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_birthday_user_name_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.EmailField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.EmailField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.EmailField(blank=True, default='', max_length=256),
        ),
    ]
