# Generated by Django 4.0.5 on 2022-06-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_address_alter_user_city_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Mail'), ('F', 'Femail')], max_length=50),
        ),
    ]
