# Generated by Django 4.0.5 on 2022-06-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
