# Generated by Django 4.0.5 on 2022-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_game_status'),
        ('user', '0007_alter_user_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(to='shop.game'),
        ),
    ]
