# Generated by Django 4.0.5 on 2022-06-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('foundation', models.DateField()),
                ('logo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=240)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=240)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('banner', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('start_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('release_year', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('old_price', models.PositiveIntegerField()),
                ('buys', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.company')),
                ('devices', models.ManyToManyField(to='shop.device')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.genre')),
                ('languages', models.ManyToManyField(to='shop.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
