# Generated by Django 4.0.5 on 2022-06-10 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='promos',
            field=models.ManyToManyField(to='shop.promo'),
        ),
        migrations.AddField(
            model_name='game',
            name='screenshots',
            field=models.ManyToManyField(to='shop.screenshot'),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.status'),
        ),
    ]
