# Generated by Django 4.0.5 on 2022-06-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='screenshots',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.game'),
            preserve_default=False,
        ),
    ]
