# Generated by Django 4.0.5 on 2022-06-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_game_screenshots_screenshot_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.AddField(
            model_name='game',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
