# Generated by Django 4.0.5 on 2022-06-11 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_alter_company_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='buys',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='old_price',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='promos',
            field=models.ManyToManyField(blank=True, to='shop.promo'),
        ),
    ]
