# Generated by Django 4.0.5 on 2022-06-23 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='shop.game'),
        ),
    ]
