# Generated by Django 4.0.5 on 2022-06-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_screenshot_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='shop.game'),
        ),
    ]
